package formularios;

import classes.Carro;
import classes.Cliente;
import dados.CarroDados;
import dados.ClienteDados;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mabel
 */
public class FPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FPrincipal
     */
    public FPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarro = new javax.swing.JTable();
        novoCarro = new javax.swing.JButton();
        alterarCarro = new javax.swing.JButton();
        excluirCarro = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        buscarCarro = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        buscarCliente = new javax.swing.JButton();
        excluirCliente = new javax.swing.JButton();
        alterarCliente = new javax.swing.JButton();
        novoCliente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblLocacao = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        buscarLocacao = new javax.swing.JButton();
        excluirLocacao = new javax.swing.JButton();
        alterarLocacao = new javax.swing.JButton();
        novaLocacao = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCarro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Marca", "Modelo", "Ano", "ValorDiario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCarro);

        novoCarro.setText("Novo");
        novoCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoCarroActionPerformed(evt);
            }
        });

        alterarCarro.setText("Alterar");
        alterarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarCarroActionPerformed(evt);
            }
        });

        excluirCarro.setText("Excluir");
        excluirCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirCarroActionPerformed(evt);
            }
        });

        buscarCarro.setText("Buscar");
        buscarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCarroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarCarro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(excluirCarro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alterarCarro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(novoCarro)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoCarro)
                    .addComponent(alterarCarro)
                    .addComponent(excluirCarro)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarCarro))
                .addGap(0, 56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Carros", jPanel1);

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Endereço", "CPF ou CNPJ", "CNH", "Dt Nascimento", "Desconto PJ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCliente.setColumnSelectionAllowed(true);
        jScrollPane3.setViewportView(tblCliente);
        tblCliente.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        buscarCliente.setText("Buscar");
        buscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClienteActionPerformed(evt);
            }
        });

        excluirCliente.setText("Excluir");
        excluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirClienteActionPerformed(evt);
            }
        });

        alterarCliente.setText("Alterar");
        alterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarClienteActionPerformed(evt);
            }
        });

        novoCliente.setText("Novo");
        novoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(excluirCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alterarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(novoCliente)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoCliente)
                    .addComponent(alterarCliente)
                    .addComponent(excluirCliente)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarCliente))
                .addGap(0, 56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes", jPanel3);

        tblLocacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Dt Locação", "Dt Entrega", "Dias Locado", "Valor Total", "Carro", "Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblLocacao);

        buscarLocacao.setText("Buscar");
        buscarLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarLocacaoActionPerformed(evt);
            }
        });

        excluirLocacao.setText("Excluir");
        excluirLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirLocacaoActionPerformed(evt);
            }
        });

        alterarLocacao.setText("Alterar");
        alterarLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarLocacaoActionPerformed(evt);
            }
        });

        novaLocacao.setText("Novo");
        novaLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaLocacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarLocacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(excluirLocacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alterarLocacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(novaLocacao)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novaLocacao)
                    .addComponent(alterarLocacao)
                    .addComponent(excluirLocacao)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarLocacao))
                .addGap(0, 56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Locações", jPanel2);

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Carro");

        jMenuItem2.setText("Incluir Carro");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Cliente");

        jMenuItem3.setText("Incluir Cliente");
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Locacao");

        jMenuItem4.setText("Incluir Locacao");
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCarroActionPerformed
        
            if(jTextField1.getText().trim().equals("")){
                this.carregarTabelaCarro(CarroDados.lstCarros);
                
            }else{
                List<Carro> carrosTemp =
                CarroDados.obterCarroPeloNomeParcial(
                    jTextField1.getText().trim(),
                    CarroDados.lstCarros,
                    false);
                this.carregarTabelaCarro(carrosTemp);
            }
            
    }//GEN-LAST:event_buscarCarroActionPerformed

    private void excluirCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirCarroActionPerformed
        try{

            if(CarroDados.lstCarros.size() > 0){

                String placa = tblCarro.
                getValueAt(tblCarro.getSelectedRow(), 0).toString();

                Carro c = CarroDados.obterCarroPeloNomeExato(
                    placa,
                    CarroDados.lstCarros);

                if(c != null){

                    if(JOptionPane.showConfirmDialog(this,
                        "Deseja apagar " + c.getPlaca() + "?",
                        "Agenda",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
                    CarroDados.lstCarros.remove(c);
                    this.carregarTabelaCarro(CarroDados.lstCarros);
                }
            }
        }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,
                "Não foi possível excluir o carro.\n\n" + ex.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_excluirCarroActionPerformed

    private void alterarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarCarroActionPerformed
        try{

            if(CarroDados.lstCarros.size() > 0){
                Carro c = CarroDados.lstCarros.get(tblCarro.getSelectedRow());
                if(c != null){

                    if(JOptionPane.showConfirmDialog(this,
                        "Deseja alterar " + c.getPlaca() + "?",
                        "Agenda",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){

                    FCadCarro frmCadCarro = new FCadCarro(this, true);
                    Carro carro = frmCadCarro.execute(c);

                    this.carregarTabelaCarro(CarroDados.lstCarros);
                }
            }
        }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,
                "Nenhum carro foi selecionado. \n\n" + ex.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_alterarCarroActionPerformed

    private void novoCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoCarroActionPerformed

        FCadCarro frmCadCarro = new FCadCarro(this, true);
        Carro c = frmCadCarro.execute();
        
        if(c != null){
            CarroDados.lstCarros.add(c);
            this.carregarTabelaCarro(CarroDados.lstCarros);
        }
    }//GEN-LAST:event_novoCarroActionPerformed

    private void buscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClienteActionPerformed
        
    }//GEN-LAST:event_buscarClienteActionPerformed

    private void excluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirClienteActionPerformed
             
    }//GEN-LAST:event_excluirClienteActionPerformed

    private void alterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarClienteActionPerformed
        try{
            
            if(ClienteDados.lstClientes.size() > 0){
                Cliente p = ClienteDados.lstClientes.get(tblCliente.getSelectedRow());
                if(p != null){
                    
                    if(JOptionPane.showConfirmDialog(this, 
                            "Deseja alterar " + p.getNome() + "?", 
                            "Agenda", 
                            JOptionPane.YES_NO_OPTION, 
                                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
                        
                        FCadCliente frmCadCliente = new FCadCliente(this, true);
                        Cliente cliente = frmCadCliente.execute(p);
                                                
                        this.carregarTabelaCliente(ClienteDados.lstClientes);                
                    }
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, 
                    "Não foi possível alterar a pessoa.\n\n" + ex.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_alterarClienteActionPerformed

    private void novoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoClienteActionPerformed
       FCadCliente frmCadCliente = new FCadCliente(this, true);
        Cliente p = frmCadCliente.execute();
        
        if(p != null){
            ClienteDados.lstClientes.add(p);
            this.carregarTabelaCliente(ClienteDados.lstClientes);
        }
           
    }//GEN-LAST:event_novoClienteActionPerformed

    private void buscarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarLocacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarLocacaoActionPerformed

    private void excluirLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirLocacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excluirLocacaoActionPerformed

    private void alterarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarLocacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alterarLocacaoActionPerformed

    private void novaLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaLocacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novaLocacaoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void carregarTabelaCarro(List<Carro> listaCarro) {
        try {
            DefaultTableModel modelo = (DefaultTableModel) tblCarro.getModel();
            modelo.getDataVector().removeAllElements();
            
            if (listaCarro.size() != 0) {
                for (Carro carro : listaCarro) {

                    SimpleDateFormat f = new SimpleDateFormat("yyyy");
                    Vector v = new Vector();
                    v.add(carro.getPlaca());
                    v.add(carro.getMarca());
                    v.add(carro.getModelo());
                    v.add(f.format(carro.getAno()));
                    v.add(Double.toString(carro.getValorDiariaLocacao()));

                    modelo.addRow(v);
                }
            } 
            else {
                Vector v = new Vector();
                v.add("Nenhum carro encontrado");
                modelo.addRow(v);
                //#TODO Descobrir com retonar o erro sem coluna
           }
            tblCarro.repaint();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível carregar os carros.\n\n" + ex.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void carregarTabelaCliente(List<Cliente> listaCliente){
        try{
            DefaultTableModel modelo = (DefaultTableModel)tblCliente.getModel();
            modelo.getDataVector().removeAllElements();
            
                       
            for (Cliente cliente : listaCliente) {
            
                SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
                
                Vector v = new Vector();                
                v.add(cliente.getNome());
                v.add(cliente.getEndereco());
                v.add(cliente.getCpfOuCnpj());
                v.add(cliente.getCnhOuCnhr());
                v.add(f.format(cliente.getDtNascimento()));
                v.add(Double.toString(cliente.getDesconto()));
                
                modelo.addRow(v);
                             
            }
            
            tblCliente.repaint();            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, 
                    "Não foi possível carregar as pessoas.\n\n" + ex.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarCarro;
    private javax.swing.JButton alterarCliente;
    private javax.swing.JButton alterarLocacao;
    private javax.swing.JButton buscarCarro;
    private javax.swing.JButton buscarCliente;
    private javax.swing.JButton buscarLocacao;
    private javax.swing.JButton excluirCarro;
    private javax.swing.JButton excluirCliente;
    private javax.swing.JButton excluirLocacao;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton novaLocacao;
    private javax.swing.JButton novoCarro;
    private javax.swing.JButton novoCliente;
    private javax.swing.JTable tblCarro;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTable tblLocacao;
    // End of variables declaration//GEN-END:variables
}
